"""ToS acceptance gate for the grievance PDFs.

The PDFs generated by griever are AVM output framed as a tax-grievance
filing. Until counsel signs off on the AVM/practicing-appraisal question
(see project_griever_legal in auto-memory), every download must be preceded
by a one-screen acknowledgement.

Design:
- User POSTs to /accept_tos. Server sets a signed cookie `griever_tos`
  whose payload is `{accepted_at_epoch}.{hmac}`.
- Each /grievance/* endpoint calls `require_tos_accepted(request)` before
  generating the artifact. On miss, the endpoint redirects to the gate page.
- Cookie TTL is 7 days. After that, user re-accepts.

Without auth (T1.19 is excluded for now), this is per-browser, not per-user.
A motivated user can click-through and re-click, but the legal protection is
in the record that they did — not in making it hard.
"""

import hmac
import hashlib
import os
import time

COOKIE_NAME = "griever_tos"
TTL_SECONDS = 7 * 24 * 3600


_PROCESS_DEFAULT_SECRET = os.urandom(32)


def _secret() -> bytes:
    """Server signing key. Falls back to a per-process random key so dev
    works without config; restarts then invalidate existing cookies, which is
    fine for ToS acceptance (the worst case is users re-accept)."""
    secret = os.getenv("GRIEVER_SESSION_SECRET")
    if secret:
        return secret.encode("utf-8")
    return _PROCESS_DEFAULT_SECRET


def make_cookie() -> str:
    """Mint a fresh ToS-accepted cookie value: '<ts>.<hex sig>'."""
    ts = str(int(time.time()))
    sig = hmac.new(_secret(), ts.encode("utf-8"), hashlib.sha256).hexdigest()
    return f"{ts}.{sig}"


def cookie_is_valid(value: str | None) -> bool:
    """Verify cookie signature and TTL. Constant-time signature compare."""
    if not value or "." not in value:
        return False
    ts_str, sig = value.split(".", 1)
    if not ts_str.isdigit():
        return False
    expected = hmac.new(_secret(), ts_str.encode("utf-8"), hashlib.sha256).hexdigest()
    if not hmac.compare_digest(sig, expected):
        return False
    age = int(time.time()) - int(ts_str)
    return 0 <= age <= TTL_SECONDS


def require_tos_accepted(request) -> bool:
    """Return True if the request carries a valid ToS-accepted cookie."""
    return cookie_is_valid(request.cookies.get(COOKIE_NAME))
